In [2]:
# Import necessary libraries
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

In [3]:
# Load the Benin dataset with a different encoding
benin_data = pd.read_csv('solar-measurements_benin-malanville_qc.csv', encoding='ISO-8859-1')

# Display the first few rows of the Benin dataset
print("Sample rows from Benin dataset:")
benin_data.head()

C:\Users\pc\AppData\Local\Temp\ipykernel_6856\1954219907.py:2: DtypeWarning: Columns (1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17) have mixed types. Specify dtype option on import or set low_memory=False.
  benin_data = pd.read_csv('solar-measurements_benin-malanville_qc.csv', encoding='ISO-8859-1')

Sample rows from Benin dataset:

,Timestamp,GHI,DNI,DHI,ModA,ModB,Tamb,RH,WS,WSgust,WSstdev,WD,WDstdev,BP,Cleaning,Precipitation,TModA,TModB,Comments
0,yyyy-mm-dd hh:mm,W/m²,W/m²,W/m²,W/m²,W/m²,°C,%,m/s,m/s,m/s,°N (to east),°,hPa,1 or 0,mm/min,°C,°C,NaN
1,2021-08-09 00:01,-1.2,-0.2,-1.1,0,0,26.2,93.4,0,0.4,0.1,122.1,0,998,0,0,26.3,26.2,NaN
2,2021-08-09 00:02,-1.1,-0.2,-1.1,0,0,26.2,93.6,0,0,0,0,0,998,0,0,26.3,26.2,NaN
3,2021-08-09 00:03,-1.1,-0.2,-1.1,0,0,26.2,93.7,0.3,1.1,0.5,124.6,1.5,997,0,0,26.4,26.2,NaN
4,2021-08-09 00:04,-1.1,-0.1,-1,0,0,26.2,93.3,0.2,0.7,0.4,120.3,1.3,997,0,0,26.4,26.3,NaN

In [4]:
# Load the Togo dataset with a different encoding
togo_data = pd.read_csv('solar-measurements_togo-dapaong_qc.csv', encoding='ISO-8859-1')

# Display the first few rows of the Togo dataset
print("Sample rows from Togo dataset:")
togo_data.head()

C:\Users\pc\AppData\Local\Temp\ipykernel_6856\2226864834.py:2: DtypeWarning: Columns (1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18) have mixed types. Specify dtype option on import or set low_memory=False.
  togo_data = pd.read_csv('solar-measurements_togo-dapaong_qc.csv', encoding='ISO-8859-1')

Sample rows from Togo dataset:

,Timestamp,GHI,DNI,DHI,ModA,ModB,Tamb,RH,WS,WSgust,WSstdev,WD,WDstdev,BP,Cleaning,Precipitation,TModA,TModB,GHIrsi,Comments
0,yyyy-mm-dd hh:mm,W/m²,W/m²,W/m²,W/m²,W/m²,°C,%,m/s,m/s,m/s,°N (to east),°,hPa,1 or 0,mm/min,°C,°C,W/m²,NaN
1,2021-10-25 00:01,-1.3,0,0,0,0,24.8,94.5,0.9,1.1,0.4,227.6,1.1,977,0,0,24.7,24.4,0,NaN
2,2021-10-25 00:02,-1.3,0,0,0,0,24.8,94.4,1.1,1.6,0.4,229.3,0.7,977,0,0,24.7,24.4,0,NaN
3,2021-10-25 00:03,-1.3,0,0,0,0,24.8,94.4,1.2,1.4,0.3,228.5,2.9,977,0,0,24.7,24.4,0,NaN
4,2021-10-25 00:04,-1.2,0,0,0,0,24.8,94.3,1.2,1.6,0.3,229.1,4.6,977,0,0,24.7,24.4,0,NaN

In [5]:
# Load the Sierra Leone dataset with a different encoding
sierraleone_data = pd.read_csv('solar-measurements_sierraleone-bumbuna_qc.csv', encoding='ISO-8859-1')

# Display the first few rows of the Sierra Leone dataset
print("Sample rows from Sierra Leone dataset:")
sierraleone_data.head()

C:\Users\pc\AppData\Local\Temp\ipykernel_6856\1226766103.py:2: DtypeWarning: Columns (1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17) have mixed types. Specify dtype option on import or set low_memory=False.
  sierraleone_data = pd.read_csv('solar-measurements_sierraleone-bumbuna_qc.csv', encoding='ISO-8859-1')

Sample rows from Sierra Leone dataset:

,Timestamp,GHI,DNI,DHI,ModA,ModB,Tamb,RH,WS,WSgust,WSstdev,WD,WDstdev,BP,Cleaning,Precipitation,TModA,TModB,Comments
0,yyyy-mm-dd hh:mm,W/m²,W/m²,W/m²,W/m²,W/m²,°C,%,m/s,m/s,m/s,°N (to east),°,hPa,1 or 0,mm/min,°C,°C,NaN
1,2021-10-30 00:01,-0.7,-0.1,-0.8,0,0,21.9,99.1,0,0,0,0,0,1002,0,0,22.3,22.6,NaN
2,2021-10-30 00:02,-0.7,-0.1,-0.8,0,0,21.9,99.2,0,0,0,0,0,1002,0,0,22.3,22.6,NaN
3,2021-10-30 00:03,-0.7,-0.1,-0.8,0,0,21.9,99.2,0,0,0,0,0,1002,0,0,22.3,22.6,NaN
4,2021-10-30 00:04,-0.7,0,-0.8,0,0,21.9,99.3,0,0,0,0,0,1002,0,0.1,22.3,22.6,NaN

In [6]:
# Define the numeric columns based on what's in the dataset
numeric_columns = [
    'GHI', 'DNI', 'DHI', 'ModA', 'ModB', 'Tamb', 'RH', 'WS', 
    'WSgust', 'WSstdev', 'WD', 'WDstdev', 'BP', 'Precipitation', 
    'TModA', 'TModB'
]

# Convert these columns to numeric (in case they are not already)
benin_data[numeric_columns] = benin_data[numeric_columns].apply(pd.to_numeric, errors='coerce')
sierraleone_data[numeric_columns] = sierraleone_data[numeric_columns].apply(pd.to_numeric, errors='coerce')
togo_data[numeric_columns] = togo_data[numeric_columns].apply(pd.to_numeric, errors='coerce')

# Summary statistics for these numeric columns
benin_summary = benin_data[numeric_columns].describe()
sierra_leone_summary = sierraleone_data[numeric_columns].describe()
togo_summary = togo_data[numeric_columns].describe()

# Display the summary statistics
print("Benin Dataset Summary:")
print(benin_summary)
print("\nSierra Leone Dataset Summary:")
print(sierra_leone_summary)
print("\nTogo Dataset Summary:")
print(togo_summary)

Benin Dataset Summary:
                 GHI            DNI            DHI           ModA  \
count  525600.000000  525600.000000  525600.000000  525600.000000
mean      240.559452     167.187516     115.358961     236.589496
std       331.131327     261.710501     158.691074     326.894859
min       -12.900000      -7.800000     -12.600000       0.000000
25%        -2.000000      -0.500000      -2.100000       0.000000
50%         1.800000      -0.100000       1.600000       4.500000
75%       483.400000     314.200000     216.300000     463.700000
max      1413.000000     952.300000     759.200000    1342.300000

                ModB           Tamb             RH             WS  \
count  525600.000000  525600.000000  525600.000000  525600.000000
mean      228.883576      28.179683      54.487969       2.121113
std       316.536515       5.924297      28.073069       1.603466
min         0.000000      11.000000       2.100000       0.000000
25%         0.000000      24.200000      28.800000       1.000000
50%         4.300000      28.000000      55.100000       1.900000
75%       447.900000      32.300000      80.100000       3.100000
max      1342.300000      43.800000     100.000000      19.500000

              WSgust        WSstdev             WD        WDstdev  \
count  525600.000000  525600.000000  525600.000000  525600.000000
mean        2.809195       0.473390     153.435172       8.582407
std         2.029120       0.273395     102.332842       6.385864
min         0.000000       0.000000       0.000000       0.000000
25%         1.300000       0.400000      59.000000       3.700000
50%         2.600000       0.500000     181.000000       8.600000
75%         4.100000       0.600000     235.100000      12.300000
max        26.600000       4.200000     360.000000      99.400000

                  BP  Precipitation          TModA          TModB
count  525600.000000  525600.000000  525600.000000  525600.000000
mean      994.197199       0.001905      35.246026      32.471736
std         2.474993       0.037115      14.807258      12.348743
min       985.000000       0.000000       9.000000       8.100000
25%       993.000000       0.000000      24.200000      23.600000
50%       994.000000       0.000000      30.000000      28.900000
75%       996.000000       0.000000      46.900000      41.500000
max      1003.000000       2.500000      81.000000      72.500000

Sierra Leone Dataset Summary:
                 GHI            DNI            DHI           ModA  \
count  525600.000000  525600.000000  525600.000000  525600.000000
mean      201.957515     116.376337     113.720571     206.643095
std       298.495150     218.652659     158.946032     300.896893
min       -19.500000      -7.800000     -17.900000       0.000000
25%        -2.800000      -0.300000      -3.800000       0.000000
50%         0.300000      -0.100000      -0.100000       3.600000
75%       362.400000     107.000000     224.700000     359.500000
max      1499.000000     946.000000     892.000000    1507.000000

                ModB           Tamb             RH             WS  \
count  525600.000000  525600.000000  525600.000000  525600.000000
mean      198.114691      26.319394      79.448857       1.146113
std       288.889073       4.398605      20.520775       1.239248
min         0.000000      12.300000       9.900000       0.000000
25%         0.000000      23.100000      68.700000       0.000000
50%         3.400000      25.300000      85.400000       0.800000
75%       345.400000      29.400000      96.700000       2.000000
max      1473.000000      39.900000     100.000000      19.200000

              WSgust        WSstdev             WD        WDstdev  \
count  525600.000000  525600.000000  525600.000000  525600.000000
mean        1.691606       0.363823     133.044668       7.172220
std         1.617053       0.295000     114.284792       7.535093
min         0.000000       0.000000       0.000000       0.000000
25%         0.000000       0.000000       0.000000       0.000000
50%         1.600000       0.400000     161.500000       6.200000
75%         2.600000       0.600000     234.100000      12.000000
max        23.900000       4.100000     360.000000      98.400000

                  BP  Precipitation          TModA          TModB
count  525600.000000  525600.000000  525600.000000  525600.000000
mean      999.876469       0.004806      32.504263      32.593091
std         2.104419       0.047556      12.434899      12.009161
min       993.000000       0.000000      10.700000      11.100000
25%       999.000000       0.000000      23.500000      23.800000
50%      1000.000000       0.000000      26.600000      26.900000
75%      1001.000000       0.000000      40.900000      41.300000
max      1006.000000       2.400000      72.800000      70.400000

Togo Dataset Summary:
                 GHI            DNI            DHI           ModA  \
count  525600.000000  525600.000000  525600.000000  525600.000000
mean      230.555040     151.258469     116.444352     226.144375
std       322.532347     250.956962     156.520714     317.346938
min       -12.700000       0.000000       0.000000       0.000000
25%        -2.200000       0.000000       0.000000       0.000000
50%         2.100000       0.000000       2.500000       4.400000
75%       442.400000     246.400000     215.700000     422.525000
max      1424.000000    1004.500000     805.700000    1380.000000

                ModB           Tamb             RH             WS  \
count  525600.000000  525600.000000  525600.000000  525600.000000
mean      219.568588      27.751788      55.013160       2.368093
std       307.932510       4.758023      28.778732       1.462668
min         0.000000      14.900000       3.300000       0.000000
25%         0.000000      24.200000      26.500000       1.400000
50%         4.300000      27.200000      59.300000       2.200000
75%       411.000000      31.100000      80.800000       3.200000
max      1367.000000      41.400000      99.800000      16.100000

              WSgust        WSstdev             WD        WDstdev  \
count  525600.000000  525600.000000  525600.000000  525600.000000
mean        3.229490       0.557740     161.741845      10.559568
std         1.882565       0.268923      91.877217       5.915490
min         0.000000       0.000000       0.000000       0.000000
25%         1.900000       0.400000      74.800000       6.900000
50%         2.900000       0.500000     199.100000      10.800000
75%         4.400000       0.700000     233.500000      14.100000
max        23.100000       4.700000     360.000000      86.900000

                  BP  Precipitation          TModA          TModB
count  525600.000000  525600.000000  525600.000000  525600.000000
mean      975.915242       0.001382      32.444403      33.543330
std         2.153977       0.026350      10.998334      12.769277
min       968.000000       0.000000      13.100000      13.100000
25%       975.000000       0.000000      23.900000      23.600000
50%       976.000000       0.000000      28.400000      28.400000
75%       977.000000       0.000000      40.600000      43.000000
max       983.000000       2.300000      70.400000      94.600000

In [9]:
# Check for missing values in all datasets
print("Missing values in Benin dataset:")
print(benin_data.isna().sum())

print("\nMissing values in Sierra Leone dataset:")
print(sierraleone_data.isna().sum())

print("\nMissing values in Togo dataset:")
print(togo_data.isna().sum())

# Fill missing values with the mean of their respective columns
benin_data.fillna(benin_data.mean(), inplace=True)
sierraleone_data.fillna(sierraleone_data.mean(), inplace=True)
togo_data.fillna(togo_data.mean(), inplace=True)

Missing values in Benin dataset:
Timestamp             0
GHI                   1
DNI                   1
DHI                   1
ModA                  1
ModB                  1
Tamb                  1
RH                    1
WS                    1
WSgust                1
WSstdev               1
WD                    1
WDstdev               1
BP                    1
Cleaning              0
Precipitation         1
TModA                 1
TModB                 1
Comments         525601
dtype: int64

Missing values in Sierra Leone dataset:
Timestamp             0
GHI                   1
DNI                   1
DHI                   1
ModA                  1
ModB                  1
Tamb                  1
RH                    1
WS                    1
WSgust                1
WSstdev               1
WD                    1
WDstdev               1
BP                    1
Cleaning              0
Precipitation         1
TModA                 1
TModB                 1
Comments         525601
dtype: int64

Missing values in Togo dataset:
Timestamp             0
GHI                   1
DNI                   1
DHI                   1
ModA                  1
ModB                  1
Tamb                  1
RH                    1
WS                    1
WSgust                1
WSstdev               1
WD                    1
WDstdev               1
BP                    1
Cleaning              0
Precipitation         1
TModA                 1
TModB                 1
GHIrsi                0
Comments         525601
dtype: int64

In [ ]:
# Replace negative values in GHI, DNI, and DHI columns with 0
ghi_cols = ['GHI', 'DNI', 'DHI']

benin_data[ghi_cols] = benin_data[ghi_cols].clip(lower=0)
sierraleone_data[ghi_cols] = sierraleone_data[ghi_cols].clip(lower=0)
togo_data[ghi_cols] = togo_data[ghi_cols].clip(lower=0)

print("\nNegative values replaced with 0 in GHI, DNI, and DHI columns.")

In [ ]:
# Define thresholds for identifying outliers
moda_threshold = 1000  # Example threshold for ModA and ModB
wind_speed_threshold = 50  # Example threshold for WS, WSgust

# Cap the outliers for ModA, ModB, WS, and WSgust
sensor_cols = ['ModA', 'ModB']
wind_cols = ['WS', 'WSgust']

benin_data[sensor_cols] = benin_data[sensor_cols].clip(upper=moda_threshold)
benin_data[wind_cols] = benin_data[wind_cols].clip(upper=wind_speed_threshold)

sierraleone_data[sensor_cols] = sierraleone_data[sensor_cols].clip(upper=moda_threshold)
sierraleone_data[wind_cols] = sierraleone_data[wind_cols].clip(upper=wind_speed_threshold)

togo_data[sensor_cols] = togo_data[sensor_cols].clip(upper=moda_threshold)
togo_data[wind_cols] = togo_data[wind_cols].clip(upper=wind_speed_threshold)

print("\nOutliers capped in sensor readings and wind speed data.")

In [ ]:
import matplotlib.pyplot as plt

def plot_time_series(df, column):
    df['Timestamp'] = pd.to_datetime(df['Timestamp'])
    plt.figure(figsize=(12, 6))
    plt.plot(df['Timestamp'], df[column], label=column)
    plt.xlabel('Date')
    plt.ylabel(column)
    plt.title(f'Time Series of {column}')
    plt.legend()
    plt.show()

plot_time_series(benin_data, 'GHI')
plot_time_series(sierraleone_data, 'GHI')
plot_time_series(togo_data, 'GHI')

In [ ]:
import seaborn as sns

def plot_correlation_heatmap(df):
    corr = df[['GHI', 'DNI', 'DHI', 'TModA', 'TModB']].corr()
    plt.figure(figsize=(10, 8))
    sns.heatmap(corr, annot=True, cmap='coolwarm', fmt='.2f')
    plt.title('Correlation Heatmap')
    plt.show()


plot_correlation_heatmap(benin_data)
plot_correlation_heatmap(sierraleone_data)
plot_correlation_heatmap(togo_data)

In [ ]:
def plot_wind_polar(df):
    plt.figure(figsize=(8, 8))
    plt.subplot(projection='polar')
    theta = np.deg2rad(df['WD'].dropna())
    r = df['WS'].dropna()
    plt.scatter(theta, r, c='b', alpha=0.5)
    plt.title('Wind Speed Distribution')
    plt.show()


plot_wind_polar(benin_data)
plot_wind_polar(sierraleone_data)
plot_wind_polar(togo_data)

In [ ]:
def plot_histogram(df, column):
    plt.figure(figsize=(10, 6))
    plt.hist(df[column].dropna(), bins=30, edgecolor='k', alpha=0.7)
    plt.xlabel(column)
    plt.ylabel('Frequency')
    plt.title(f'Histogram of {column}')
    plt.show()

# Example: Histogram of GHI
plot_histogram(benin_data, 'GHI')
plot_histogram(sierraleone_data, 'GHI')
plot_histogram(togo_data, 'GHI')